apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-breaker-game-server
  namespace: code-breaker-game
  labels:
    app: code-breaker-game-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-breaker-game-server
  template:
    metadata:
      labels:
        app: code-breaker-game-server
    spec:
      containers:
        - name: code-breaker-game-server
          image: code-breaker-game:latest
          imagePullPolicy: Never
          args: ["server"]
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
