apiVersion: v1
kind: Service
metadata:
  name: code-breaker-game-server-svc
  namespace: code-breaker-game
  labels:
    app: code-breaker-game-server
spec:
  selector:
    app: code-breaker-game-server
  ports:
    - name: tcp-game
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
