apiVersion: v1
kind: Service
metadata:
  name: ccs-server-svc
  namespace: ccs-game
  labels:
    app: ccs-server
spec:
  selector:
    app: ccs-server
  ports:
    - name: tcp-game
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
